#! /bin/sh
set -euf

JSESSIONID="${JSESSIONID}"

# obtain magic number (which changes every bookmarkablePage-request(?))
magic=$(
  curl -k -sS -b JSESSIONID=$JSESSIONID \
    https://banking.postbank.de/rai/?wicket:bookmarkablePage=:de.postbank.ucp.application.rai.fs.umsatzauskunft.UmsatzauskunftPage |
  sed -n 's/.*?wicket:interface=:\([^:]\+\):.*/\1/p;T;q' |
  grep .
)

# setup Umsatzauskunft to display the desired range of entries
vonDatum=`date -d "${1--99days}" +%d.%m.%Y`
bisDatum=`date -d "${2-today}" +%d.%m.%Y`
curl -k -sS -b JSESSIONID=$JSESSIONID \
  -d umsatzanzeigeGiro:salesForm:umsatzFilterOptionenAufklappbarSuchfeldPanel:gebuchtVorgemerktUmschalter:gebuchtVorgemerktUmschalterRadioGroup=radio0 \
  -d umsatzanzeigeGiro:salesForm:umsatzFilterOptionenAufklappbarSuchfeldPanel:accordion:vonBisDatum:datumForm:vonGruppe:vonDatum=$vonDatum \
  -d umsatzanzeigeGiro:salesForm:umsatzFilterOptionenAufklappbarSuchfeldPanel:accordion:vonBisDatum:datumForm:bisGruppe:bisDatum=$bisDatum \
  -o /dev/null \
  https://banking.postbank.de/rai/?wicket:interface=:$magic:umsatzauskunftContainer:umsatzauskunftpanel:panel:form::IFormSubmitListener::

# download CSV and convert to UTF-8
curl -k -sS -b JSESSIONID=$JSESSIONID \
  https://banking.postbank.de/rai/?wicket:interface=:$magic:umsatzauskunftContainer:umsatzauskunftpanel:panel:form:umsatzanzeigeGiro:umsatzaktionen:umsatzanzeigeUndFilterungDownloadlinksPanel:csvHerunterladen::IResourceListener:: |
sed "s/`printf '\x80'`/EUR/g" |
iconv -f latin1 -t utf-8
